### ISSUE TITLE
NodeJS compatibility

### ISSUE THREAD

**Issue by BenoitZugmeyer** [abozhilov/ES-Iter#14]
I saw your lib published on npm, and was going to use it but sadly it requires transpilation because of its usage of modules. You should really publish a node-compatible version on npm. My advice: transpile it with rollup in a pre-publish hook, change the `main` entry and set `esnext:main` to `src/Iter.js` in the `package.json` ([doc](https://github.com/rollup/rollup/wiki/jsnext%3Amain)).

**Comment by abozhilov** [comment]
Thanks! Definitely I'll do. Will let you know when it's updated.

**Comment by abozhilov** [comment]
Done. I added NodeJS compatible build and followed your suggestions.

**Comment by BenoitZugmeyer** [comment]
Thank you. You are using babel to compile it: the benefit is it'll work on old versions of nodejs (< 6.0.0), but right now your module isn't usable as-is, because `babel-polyfill` is a devDependency only:
```
~/ES-Iter % rm -rf node_modules
~/ES-Iter % npm install --prod
~/ES-Iter % node -e 'require(".")' 
module.js:341
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (ES-Iter/build/Iter.js:11:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

My suggestion was to use rollup to only transpile the module syntax, since node >= 6.0.0 supports all other feature your package is using.

Anyway, I finally published [my package](https://github.com/BenoitZugmeyer/iterator-tools.js), and met [the same issue](https://github.com/BenoitZugmeyer/iterator-tools.js/commit/fb73a386ecd57af38851612121d01fca4b0647b9).

**Comment by abozhilov** [comment]
Got it now, thanks! I didn't hit `close issue`, because I wasn't totally sure. 
I really want in version 1.0 to remove transpiling process entirely. Started work on that: https://github.com/abozhilov/ES-Iter/tree/1.0-devel 

This branch is fully compatible with NodeJS 6. 
One note: NodeJS 6 does not support closing iterators on abrupt exits, e.g. `break`, `throw`, `return`. Even that, the lib works as expected. Pretty much happy to test it without transpiling. 

I'm going to test it in last browser versions and those days will publish 1.0.0 with `engineStrict` in `package.json`. In future version will follow same pattern and will update it to use ES6 modules export.
